<template>
   <ContentTemplate>
       <h1>This is Terms and Conditions page</h1>
       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos illo nisi perspiciatis quaerat quidem rem. Amet asperiores earum eveniet fugit in ipsam laudantium nobis quod sint veniam! Dolorem minima molestias pariatur perferendis repellendus soluta ullam veritatis. Aut eum illum labore molestiae nam nemo perspiciatis sint. Ad alias aliquid incidunt molestias numquam quae rerum vitae. A ab accusamus, ad amet consequatur debitis distinctio dolores ducimus ea eligendi et exercitationem explicabo id ipsam minus, molestias omnis optio perferendis, porro sed sint soluta suscipit? Accusantium, adipisci atque consequatur corporis deleniti doloremque esse eveniet hic in labore optio qui quis quod recusandae rem repellat repudiandae sapiente sint. Ea optio, quae quasi qui sit velit voluptatum! Adipisci aperiam, at aut commodi consectetur debitis exercitationem ipsa ipsam ipsum, itaque minima natus nesciunt nobis officiis perspiciatis quidem, quo recusandae rerum soluta tempora? Accusantium, blanditiis eius, enim exercitationem illo laudantium magnam modi non perferendis quaerat quis sed, ut! A accusamus animi asperiores at aut autem dignissimos distinctio dolorem dolores doloribus eaque est, eveniet id laboriosam molestiae nam, non obcaecati optio porro praesentium quasi quia quo repellendus saepe sequi sit veritatis voluptate. Aliquam animi assumenda dolore doloribus eaque error et excepturi iusto nesciunt possimus quam quasi quisquam, quod sequi!</p>
       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos illo nisi perspiciatis quaerat quidem rem. Amet asperiores earum eveniet fugit in ipsam laudantium nobis quod sint veniam! Dolorem minima molestias pariatur perferendis repellendus soluta ullam veritatis. Aut eum illum labore molestiae nam nemo perspiciatis sint. Ad alias aliquid incidunt molestias numquam quae rerum vitae. A ab accusamus, ad amet consequatur debitis distinctio dolores ducimus ea eligendi et exercitationem explicabo id ipsam minus, molestias omnis optio perferendis, porro sed sint soluta suscipit? Accusantium, adipisci atque consequatur corporis deleniti doloremque esse eveniet hic in labore optio qui quis quod recusandae rem repellat repudiandae sapiente sint. Ea optio, quae quasi qui sit velit voluptatum! Adipisci aperiam, at aut commodi consectetur debitis exercitationem ipsa ipsam ipsum, itaque minima natus nesciunt nobis officiis perspiciatis quidem, quo recusandae rerum soluta tempora? Accusantium, blanditiis eius, enim exercitationem illo laudantium magnam modi non perferendis quaerat quis sed, ut! A accusamus animi asperiores at aut autem dignissimos distinctio dolorem dolores doloribus eaque est, eveniet id laboriosam molestiae nam, non obcaecati optio porro praesentium quasi quia quo repellendus saepe sequi sit veritatis voluptate. Aliquam animi assumenda dolore doloribus eaque error et excepturi iusto nesciunt possimus quam quasi quisquam, quod sequi!</p>
   </ContentTemplate>
</template>

<script setup lang="ts">
import ContentTemplate from '@/components/ContentTemplate.vue'
</script>

<style lang="scss">

</style>
